//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class cliente
    {
        public cliente()
        {
            this.servicio = new HashSet<servicio>();
        }
    
        public int id_cliente { get; set; }
        public int fkPersona { get; set; }
        public int Direccion { get; set; }
        public System.DateTime fecha_creacion_c { get; set; }
    
        public virtual ICollection<servicio> servicio { get; set; }
    }
}
