//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class enfermedades
    {
        public enfermedades()
        {
            this.servicio = new HashSet<servicio>();
        }
    
        public int idEnfermedad { get; set; }
        public string descEnfermedad { get; set; }
        public int fkTipoEnf { get; set; }
    
        public virtual tipoenfermedad tipoenfermedad { get; set; }
        public virtual ICollection<servicio> servicio { get; set; }
    }
}
