//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class estudiante
    {
        public int idEstudiante { get; set; }
        public long Telefono { get; set; }
        public int fkTutor { get; set; }
    
        public virtual docente docente { get; set; }
        public virtual persona persona { get; set; }
    }
}
