//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class mascota
    {
        public mascota()
        {
            this.vacunas_mascota = new HashSet<vacunas_mascota>();
            this.servicio = new HashSet<servicio>();
        }
    
        public int idMascota { get; set; }
        public int fkPersona { get; set; }
        public int nombreMasc { get; set; }
        public int tipoMasc { get; set; }
        public int Raza { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
    
        public virtual persona persona { get; set; }
        public virtual raza raza1 { get; set; }
        public virtual tipomascota tipomascota { get; set; }
        public virtual ICollection<vacunas_mascota> vacunas_mascota { get; set; }
        public virtual ICollection<servicio> servicio { get; set; }
    }
}
