//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class medicacion
    {
        public int id_medicacion_servicio { get; set; }
        public int Cantidad { get; set; }
        public string Medicamento { get; set; }
        public string Posologia { get; set; }
    
        public virtual servicio servicio { get; set; }
    }
}
