//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class vetonline3Entities : DbContext
    {
        public vetonline3Entities()
            : base("name=vetonline3Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<cliente> cliente { get; set; }
        public DbSet<dia> dia { get; set; }
        public DbSet<docente> docente { get; set; }
        public DbSet<enfermedades> enfermedades { get; set; }
        public DbSet<estudiante> estudiante { get; set; }
        public DbSet<estudios_previos> estudios_previos { get; set; }
        public DbSet<evaluacion_servicio> evaluacion_servicio { get; set; }
        public DbSet<horas> horas { get; set; }
        public DbSet<mascota> mascota { get; set; }
        public DbSet<medicacion> medicacion { get; set; }
        public DbSet<persona> persona { get; set; }
        public DbSet<raza> raza { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<servicio> servicio { get; set; }
        public DbSet<tipoenfermedad> tipoenfermedad { get; set; }
        public DbSet<tipomascota> tipomascota { get; set; }
        public DbSet<vacunas> vacunas { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
        public DbSet<vacunas_mascota> vacunas_mascota { get; set; }
    }
}
