//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.mascota = new HashSet<mascota>();
        }
    
        public int Identificacion { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int fkRol { get; set; }
    
        public virtual docente docente { get; set; }
        public virtual estudiante estudiante { get; set; }
        public virtual ICollection<mascota> mascota { get; set; }
    }
}
