//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio
    {
        public int idServicio { get; set; }
        public int fkCliente { get; set; }
        public int fkMedico { get; set; }
        public int fkMascota { get; set; }
        public string Estado { get; set; }
        public string Descripcion { get; set; }
        public System.DateTime fecha_servicio { get; set; }
        public int fkEnfermedad { get; set; }
        public int fkHora { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual docente docente { get; set; }
        public virtual enfermedades enfermedades { get; set; }
        public virtual evaluacion_servicio evaluacion_servicio { get; set; }
        public virtual horas horas { get; set; }
        public virtual mascota mascota { get; set; }
        public virtual medicacion medicacion { get; set; }
    }
}
