//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipoenfermedad
    {
        public tipoenfermedad()
        {
            this.enfermedades = new HashSet<enfermedades>();
        }
    
        public int id_tipo_enfermedad { get; set; }
        public string tipoEnf { get; set; }
    
        public virtual ICollection<enfermedades> enfermedades { get; set; }
    }
}
