//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VetOnlineBeta
{
    using System;
    using System.Collections.Generic;
    
    public partial class vacunas_mascota
    {
        public int idVacuna { get; set; }
        public int idMascota { get; set; }
        public System.DateTime fechaAplicacion { get; set; }
    
        public virtual mascota mascota { get; set; }
        public virtual vacunas vacunas { get; set; }
    }
}
